# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22b6eebcfedfd7541211ef4365e9dfc5849ee9cbbd46de515fc7a2c6601c7a0b9828ad79c61708c5dda338c235d7e371cfd93b80b1309c850c5ad5a976009892

test:
  secret_key_base: 7e9a83fbfcf2169600f3955738e5f233a5967503fcb4f4d45f0ee97534280679f459422a00dfc18e3113eb51c66563fc83865e46180af81a2a710366a3a725e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
